name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug - List Files
        run: ls -R  

      - name: Install Dependencies
        run: npm install  

      - name: Run Build
        run: npm run build  

      - name: Verify Build Output
        run: ls -R dist  
