name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Navigate to Frontend and Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Build
        run: |
          cd frontend
          npm run build
